export const ACTIONS = {
  SHOW_MENU: 'MENU',
  BUILD_PLATE: 'BUILD_PLATE',
  RESET_ORDER: 'RESET_ORDER',
  CONFIRM_ORDER: 'CONFIRM_ORDER',
  CONFIRM_DIRECTION: 'CONFIRM_DIRECTION',
  SHIPPING_INFORMATION: 'SHIPPING_INFORMATION',
  RESET_SHIPPING_INFORMATION: 'RESET_SHIPPING_INFORMATION',
  CONFIRM_OPTIONS: 'CONFIRM_OPTION',
  RESET_OPTIONS: 'RESET_OPTION',
  GET_STARTED: 'GET_STARTED',
  FLOW_ORDER_CONFIRMATION: 'FLOW_ORDER_CONFIRMATION',
};
