export const FLOWS = {
  START_CREATE_PLATE: 'START_CREATE_PLATE',
  START_CONFIRM_ORDER: 'START_CONFIRM_ORDER',
  START_PAYMENT: 'START_PAYMENT',
  START_SHIPPING_INFORMATION: 'START_SHIPPING_INFORMATION',
  START_CONSULTANT: 'START_CONSULTANT',
};
