export enum MessengerEvent {
  STANDBY = 'standby',
  MESSAGE = 'message',
  MESSAGE_DELIVERED = 'delivery',
  MESSAGE_READ = 'read',
  MESSAGE_ECHO = 'echo',
  POSTBACK = 'postback',
  OPTIN = 'optin',
  REFERRAL = 'referral',
  PAYMENTS = 'payment',
  CHECKOUT_UPDATE = 'checkout_update',
  ACCOUNT_LINKING = 'account_linking',
  PASS_THREAD_CONTROL = 'pass_thread_control',
  TAKE_THREAD_CONTROL = 'take_thread_control',
  REQUEST_THREAD_CONTROL = 'request_thread_control',
  APP_ROLES = 'app_roles',
  UNKNOWN = 'unknown',
}
