# name: Deploy

# on:
#   push:
#     branches:
#       - develop
#       - main

# concurrency: ${{github.workflow}}-${{github.workflow}}

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: run ssh commands
#         uses: fifsky/ssh-action@master
#         with:
#           command: |
#            cd repo && git pull &&
#            cd admin &&

